---

# Set Time Zone
# Manual Shell: echo '{{ timezone_locale }}' | sudo tee /etc/timezone > /dev/null
- name: Update Timezone
  copy: content="{{ timezone_locale }}\n" dest=/etc/timezone owner=root group=root mode=0644
  become: yes
  register: timezone

# Debian Only
- name: Reconfigure Timezone Data
  shell: dpkg-reconfigure -f noninteractive tzdata
  become: yes
  when: timezone.changed
